// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vtt.Server.Infrastructure;

#nullable disable

namespace Vtt.Server.Infrastructure.Migrations
{
    [DbContext(typeof(VttDbContext))]
    [Migration("20260805160238_AddCampaignRoster")]
    partial class AddCampaignRoster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vtt.Server.Accounts.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<Guid?>("ConsumedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("ConsumedByUserId")
                        .HasDatabaseName("ix_invites_consumed_by_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_invites_created_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_token_hash");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Vtt.Server.Accounts.RecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recovery_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_recovery_codes_code_hash");

                    b.HasIndex("IssuedByUserId")
                        .HasDatabaseName("ix_recovery_codes_issued_by_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recovery_codes_user_id");

                    b.ToTable("recovery_codes", (string)null);
                });

            modelBuilder.Entity("Vtt.Server.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username_normalized");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username_normalized");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Vtt.Server.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("system_id");

                    b.Property<string>("SystemVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("system_version");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("Vtt.Server.Campaigns.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_campaign_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_campaign_members_user_id");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_campaign_members_campaign_id_user_id");

                    b.ToTable("campaign_members", (string)null);
                });

            modelBuilder.Entity("Vtt.Server.Accounts.Invite", b =>
                {
                    b.HasOne("Vtt.Server.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("ConsumedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invites_user_consumed_by_user_id");

                    b.HasOne("Vtt.Server.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invites_user_created_by_user_id");
                });

            modelBuilder.Entity("Vtt.Server.Accounts.RecoveryCode", b =>
                {
                    b.HasOne("Vtt.Server.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_codes_user_issued_by_user_id");

                    b.HasOne("Vtt.Server.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recovery_codes_user_user_id");
                });

            modelBuilder.Entity("Vtt.Server.Campaigns.CampaignMember", b =>
                {
                    b.HasOne("Vtt.Server.Campaigns.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_members_campaigns_campaign_id");

                    b.HasOne("Vtt.Server.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_members_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
